baseurl = "https://theking009.github.io"
title = "The King Portfolio"

theme = "hugo-coder"
languagecode = "en"

defaultcontentlanguage = "en"



[params]
    author = "Aayush Kashyap"
    description = "Game Dev. Web Dev. Environmental Enthusiast"
    keywords = "blog,developer,personal"
    info = "Game Dev. Web Dev. Environmental Enthusiast"
    avatarURL = "images/avatar.jpg"
    #gravatar = "kashyapaayush32@gmail.com"
    footerContent = "Programmers know what works confuses more than what doesn't."

    dateFormat = "January 2, 2006"

    hideFooter = false
    hideCredits = true
    hideCopyright = true
    since = 2019
    
    colorScheme = "auto"
    hideColorSchemeToggle = false

    maxSeeAlsoItems = 5
    enableTwemoji = true

[params.csp]
	  childsrc = ["'self'"]
	  fontsrc = [
        "'self'",
		    "https://fonts.gstatic.com",
		    "https://cdn.jsdelivr.net/"
    ]
	  formaction = ["'self'"]
	  framesrc = ["'self'"]
	  imgsrc = ["'self'"]
	  objectsrc = ["'none'"]
	  stylesrc = [
        "'self'",
		    "'unsafe-inline'",
		    "https://fonts.googleapis.com/",
		    "https://cdn.jsdelivr.net/"
    ]
	  scriptsrc = [
        "'self'",
		    "'unsafe-inline'",
		    "https://www.google-analytics.com"
    ]
	  prefetchsrc = ["'self'"]

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/TheKing009/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 2
    url = "https://twitter.com/CyberCopAayush/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/aayush-kashyap-ba5b751b0/"

[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            #[[languages.en.menu.main]]
            #name = "Blog"
            #weight = 2
            #url = "posts/"

            #[[languages.en.menu.main]]
            #name = "Projects"
            #weight = 3
            #url = "projects/"

            #[[languages.en.menu.main]]
            #name = "Contact me"
            #weight = 2 
            #url = "contact/"